SYMBOLS_64_STOCKS = {
    'SPY': 'AMEX:SPY',
    'RSP': 'AMEX:RSP',
    'QQQ': 'NASDAQ:QQQ',
    'QQQE': 'NASDAQ:QQQE',
    'DIA': 'AMEX:DIA',
    'IWM': 'AMEX:IWM',
    'VO': 'AMEX:VO',
    'XLC': 'AMEX:XLC',
    'XLP': 'AMEX:XLP',
    'XLY': 'AMEX:XLY',
    'XLE': 'AMEX:XLE',
    'XLF': 'AMEX:XLF',
    'XLV': 'AMEX:XLV',
    'XLI': 'AMEX:XLI',
    'XLB': 'AMEX:XLB',
    'XLRE': 'AMEX:XLRE',
    'XLK': 'AMEX:XLK',
    'XLU': 'AMEX:XLU',
    'BIL': 'AMEX:BIL',
    'SHY': 'NASDAQ:SHY',
    'IEI': 'NASDAQ:IEI',
    'IEF': 'NASDAQ:IEF',
    'TLT': 'NASDAQ:TLT',
    'EDV': 'AMEX:EDV',
    'HYG': 'AMEX:HYG',
    'LQD': 'AMEX:LQD',
    'FALN': 'NASDAQ:FALN',
    'FLOT': 'AMEX:FLOT',
    'MUB': 'AMEX:MUB',
    'EMLC': 'AMEX:EMLC',
    'EMB': 'NASDAQ:EMB',
    'VEU': 'AMEX:VEU',
    'EZU': 'AMEX:EZU',
    'EWI': 'AMEX:EWI',
    'EWP': 'AMEX:EWP',
    'EWQ': 'AMEX:EWQ',
    'EWG': 'AMEX:EWG',
    'EPOL': 'AMEX:EPOL',
    'EZA': 'AMEX:EZA',
    'EWJ': 'AMEX:EWJ',
    'DXJ': 'AMEX:DXJ',
    'ASHR': 'AMEX:ASHR',
    'FXI': 'AMEX:FXI',
    'ASHS': 'AMEX:ASHS',
    'EWH': 'AMEX:EWH',
    'EWS': 'AMEX:EWS',
    'EIDO': 'AMEX:EIDO',
    'THD': 'AMEX:THD',
    'EWM': 'AMEX:EWM',
    'KWEB': 'AMEX:KWEB',
    'SCJ': 'AMEX:SCJ',
    'EWZ': 'AMEX:EWZ',
    'EWZS': 'NASDAQ:EWZS',
    'EWW': 'AMEX:EWW',
    'ECH': 'AMEX:ECH',
    'EWC': 'AMEX:EWC',
    'GSG': 'AMEX:GSG',
    'USO': 'AMEX:USO',
    'CPER': 'AMEX:CPER',
    'UNL': 'AMEX:UNL',
    'UNG': 'AMEX:UNG',
    'DBA': 'AMEX:DBA',
    'WEAT': 'AMEX:WEAT',
}

SYMBOLS_LATIN_AMERICA = {
    'EWZ': 'AMEX:EWZ',
    'EWW': 'AMEX:EWW',
    'ILF': 'AMEX:ILF',
    'IEF': 'NASDAQ:IEF',
    'TLT': 'NASDAQ:TLT',
    'CL1!': 'NYMEX:CL1!',
    'HG1!': 'COMEX:HG1!',
    'IRX.P': 'CBOE:IRX.P',
    'BIL': 'AMEX:BIL',
    'USO': 'AMEX:USO',
    'CPER': 'AMEX:CPER',
}

SYMBOLS_TREASURY = {
    'TLT': 'NASDAQ:TLT',
    'BIL': 'AMEX:BIL',
    'SHY': 'NASDAQ:SHY',
    'IEI': 'NASDAQ:IEI',
    'IEF': 'NASDAQ:IEF',
}

SYMBOLS_JPX = {
    'NISSAN MOTOR': 'TSE:7201',
    'ISUZU MOTORS': 'TSE:7202',
    'TOYOTA MOTOR': 'TSE:7203',
    'HINO MOTORS': 'TSE:7205',
    'MITSUBISHI MOTORS': 'TSE:7211',
    'MAZDA MOTOR': 'TSE:7261',
    'HONDA MOTOR': 'TSE:7267',
    'SUZUKI MOTOR': 'TSE:7269',
    'SUBARU': 'TSE:7270',
    'YAMAHA MOTOR': 'TSE:7272',
}
